In [7]:
import pandas as pd
from sklearn.model_selection  import train_test_split
from category_encoders import target_encoder

In [8]:
d={'product':['kiki','oooo','pppp','pppp','kiki','kiki','oooo','oooo','oooo','oooo'],
   'tpyes':['maggi','yeepi','maggi','maggi','maggi','yeepi','dosa','dosa','maggi','dosa'],
   'target':[100,200,300,400,500,600,600,700,800,900]}

In [9]:
df=pd.DataFrame(d)
df

  product  tpyes  target
0    kiki  maggi     100
1    oooo  yeepi     200
2    pppp  maggi     300
3    pppp  maggi     400
4    kiki  maggi     500
5    kiki  yeepi     600
6    oooo   dosa     600
7    oooo   dosa     700
8    oooo  maggi     800
9    oooo   dosa     900

In [10]:
xtrain=df.drop(columns='target')
ytrain=df['target']

In [11]:
xtrain,xtest,ytrain,ytest=train_test_split(xtrain,ytrain,train_size=0.8,random_state=42)

In [17]:
from category_encoders import TargetEncoder

encoder = TargetEncoder(handle_unknown='value')

In [26]:
encoder.fit_transform(xtrain,ytrain)

      product       tpyes
5  495.122658  523.884492
0  495.122658  481.003447
7  546.611079  546.611079
2  489.449202  481.003447
9  546.611079  546.611079
4  495.122658  481.003447
3  489.449202  481.003447
6  546.611079  546.611079

In [27]:
encoder.transform(xtest,ytest)

      product       tpyes
8  546.611079  481.003447
1  546.611079  523.884492